### ISSUE TITLE
Missing capability name string

### ISSUE THREAD

**Issue by mudrd8mz** [marceloschmitt/moodle-local_delete_course#1]
![image](https://user-images.githubusercontent.com/85831/128492860-0d6e9d4d-2115-487f-adbb-4fb796c10b3c.png)

**Comment by marceloschmitt** [comment]
Is it possible that you do not have the last version? As you may see, it it there. 

$string['pluginname'] = 'Delete course';
$string['delete_course'] = 'Delete course';
$string['alert'] = 'Attention! If you continue this operation the course you are in will be deleted. Think about downloading a backup.';
$string['deletingcourse'] = 'Deleting course';
$string['deletedcourse'] = 'Deleted course:';

**Comment by mudrd8mz** [comment]
Have you tried to visit Users permission page with your plugin installed (and developer debugging enabled). Please see the string identifier in the debug message - there is no string with identifier `delete_course:manage`

**Comment by marceloschmitt** [comment]
Thanks a lot. Added $string['delete_course:manage'] = 'Delete own courses';
