### ISSUE TITLE
Support for Moddle 4+

### ISSUE THREAD

**Issue by Shotte** [marceloschmitt/moodle-local_delete_course#2]
Hi there, is there any chance to get an update of your plugin with an official support for newer Moodle releases >4, e.g 4.4 or even better 4.5 LTS? I currently use it in 4.3 and ist seems to work, but Moodle plugin repository says that the plugin is only compatible up to Moodle 3.11.

Thank you!

**Comment by marceloschmitt** [comment]
I have finished correcting all messagens for Moodle 4.4. I have also teste it. Now I will save a release and also create a new version in Moodle directory.
